---
title: "Visualizaciones Preliminares: Departamento del Trabajo y Recursos Humanos"
author: "Félix A Báez Santiago"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Imports
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(zoo)
library(kableExtra)
library(here)
path <- here("data", "departamento_de_trabajo", "/")
```

## Tasa de participación laboral según el año natural y el sexo
```{r, echo=FALSE}
# importando el dataset de Casos en Supervisión de Ley 54
dtPartlab <- read_excel(paste0(path, "dtpartlab.xlsx")) %>%
  filter(Género != "Ambos") %>%
  pivot_longer(!Género, names_to = "Año", values_to = "Cantidad") %>%
  mutate(
    Año = factor(Año)
  )
dtPartlab
```

```{r, echo=FALSE}
ggplot(dtPartlab, aes(x = Año, y = Cantidad, color = Género, group = Género)) +
  geom_line(size = 1) +
  geom_point(size = 3) +
  labs(title = "1. Tasa de participación laboral por género y año", x = "Año", y = "Porcentaje Laboral") +
  theme_minimal() + 
  scale_y_continuous(limits = c(0, NA))

ggplot(dtPartlab, aes(x = Género, y = Cantidad, fill = Año)) +
  geom_bar(stat = "identity") +
  labs(title = "2. Tasa de participación laboral por género y año", x = "Género", y = "Cantidad") +
  theme_minimal()

ggplot(dtPartlab, aes(x = Género, y = Cantidad, fill = Año)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "3. Tasa de participación laboral por género y año", x = "Género", y = "Cantidad") +
  theme_minimal()

ggplot(dtPartlab, aes(x = Año, y = Cantidad, fill = Género)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = " Tasa de participación laboral por sexo y año", x = "Año", y = "Tasa", fill = "Sexo") +
  theme_minimal()

renderBarPlottest(dtPartlab, x = "Año", y = "Cantidad", fill = "Género",
                       paste("Tasa de participación laboral por sexo y año"),
                       xlab = "Año", ylab = "Número de Casos", fillLab = "Tipo de Incidente")
```