---
title: "Funcionalidad de Mapas"
author: "Félix A Báez Santiago"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, echo=FALSE, message=FALSE}
library(leaflet)
library(tidyverse)
library(readxl)
library(zoo)
library(here)
library(lubridate)
library(sf)
library(plotly)
path <- here("data", "Departamento_de_Justicia//")
path2 <- here("data", "mapas/")
```

Funcion para manejar datos missing
```{r, warning=FALSE, echo=FALSE, message=FALSE}
# funcion para convertir columna con varios tipos de datos a numerico
convert_mixed_columns <- function(data) {
  mixed_columns <- sapply(data, function(col) any(is.character(col) & !is.na(as.numeric(col))))
  mixed_columns_names <- names(mixed_columns)[mixed_columns]
  
  for (col in mixed_columns_names) {
    data[[col]] <- ifelse(data[[col]] == "N/A", NA, as.character(data[[col]]))
    data[[col]] <- as.numeric(data[[col]])
  }
  
  return(data)
}

### renderMap_static para static graphs
renderMap_static <- function(data, fill, title, fill_lab = fill, 
                      light_color = "lightblue", dark_color = "darkblue",
                      facet = FALSE, facet_var = NULL) {
  p <- ggplot(data) +
    geom_sf(aes(fill = {{fill}})) +
    labs(title = title, fill = fill_lab) +
    scale_fill_gradient(name = fill_lab, low = light_color, high = dark_color) +
    theme_minimal() +
    theme(
      legend.position = "bottom",
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      panel.grid = element_blank()
    )
  if (facet && !is.null(facet_var)) {
    p <- p + facet_wrap(as.formula(paste("~", facet_var)), scales = "fixed", drop = FALSE)
  }
  print(p)
}
```

## Delitos a la Ley 54, casos radicados por jurisdicción y articulo de la Ley de Violencia Domestica, año 2020 a *2023
```{r, warning=FALSE, echo=FALSE, message=FALSE}
# importando delitos del 2020
deli2020 <- read_excel(paste0(path, "djDelitos2020.xlsx")) %>% 
  convert_mixed_columns() %>%
  mutate(Año = "2020") %>% select(-TOTAL) %>%
  pivot_longer(-c(`FISCALIA DISTRITO`, Año), names_to = "Delito", values_to = "Casos") %>%
  filter(!grepl("TOTAL", `FISCALIA DISTRITO`, ignore.case = TRUE))

# importando delitos del 2021
deli2021 <- read_excel(paste0(path, "djDelitos2021.xlsx")) %>%
  convert_mixed_columns() %>%
  mutate(Año = "2021") %>% select(-TOTAL) %>% 
  pivot_longer(-c(`FISCALIA DISTRITO`, Año), names_to = "Delito", values_to = "Casos") %>%
  filter(!grepl("TOTAL", `FISCALIA DISTRITO`, ignore.case = TRUE))

# importando delitos del 2022
deli2022 <- read_excel(paste0(path, "djDelitos2022.xlsx")) %>%
  convert_mixed_columns() %>%
  mutate(Año = "2022") %>% select(-TOTAL) %>%
  pivot_longer(-c(`FISCALIA DISTRITO`, Año), names_to = "Delito", values_to = "Casos") %>%
  filter(!grepl("TOTAL", `FISCALIA DISTRITO`, ignore.case = TRUE))

# importando delitos del 2023
deli2023 <- read_excel(paste0(path, "djDelitos2023.xlsx")) %>%
  convert_mixed_columns() %>%
  mutate(Año = "2023") %>% select(-TOTAL) %>%
  pivot_longer(-c(`FISCALIA DISTRITO`, Año), names_to = "Delito", values_to = "Casos") %>%
  filter(!grepl("TOTAL", `FISCALIA DISTRITO`, ignore.case = TRUE))

dfDeli2 <- full_join(deli2020, deli2021) %>% 
  full_join(deli2022) %>%
  full_join(deli2023) %>%
  mutate(
    Año = as.factor(Año),
    `FISCALIA DISTRITO` = str_to_title(tolower(`FISCALIA DISTRITO`))
    )
class(dfDeli2)
```

```{r}
# Crear un dataframe con las coordenadas de las fiscalías policiacas
distritos_fiscales <- sf::st_read(paste0(path2, "distritos_fiscales.json"))
distritos_fiscales
```

```{r}
# Combinar los datos de delitos con los datos geográficos de los distritos fiscales
mapaDeli <- merge(distritos_fiscales, dfDeli, by.x = "GROUP", by.y = "FISCALIA DISTRITO")
mapaDeli
```

```{r}
# Seleccionar solo los datos para un tipo de delito específico
delito_seleccionado <- "Art3.5"  # Reemplaza con el delito que deseas visualizar
año_seleccionado <- c("2020","2021", "2022", "2023")

datos_delito_seleccionado <- mapaDeli %>%
  filter(
    Delito == delito_seleccionado,
    Año %in% año_seleccionado
  )

# Crear el mapa con ggplot2
mapa_delitos <- renderMap(data = mapaDeli,
            fill = Casos,
            title = paste("Incidencia de casos de", delito_seleccionado, "en el año", año_seleccionado),
            fill_lab = "Incidencia de Casos",
            light_color = "pink",
            dark_color = "darkred")
mapa_delitos

# Crear el mapa con ggplot2
mapa_delitos <- renderMap(data = mapaDeli,
            fill = Casos,
            title = paste("Incidencia de casos de", delito_seleccionado),
            fill_lab = "Incidencia de Casos",
            light_color = "pink",
            dark_color = "red")
mapa_delitos

### interactividad
mapa_interactivo <- ggplotly(mapa_delitos, 
                             tooltip = "text") %>%
  style(
    text = paste("Fiscalía:", datos_delito_seleccionado$GROUP, "<br>",
                 "Casos:", datos_delito_seleccionado$Casos, "<br>",
                 "Municipio:", datos_delito_seleccionado$NAME)
  )
# Mostrar el mapa
mapa_interactivo
```


```{r}
mapa_delitos <- renderMap_static(data = datos_delito_seleccionado, 
            fill = Casos, 
            title = paste("Incidencia de casos de", delito_seleccionado, "en el año", año_seleccionado),
            fill_lab = "Incidencia de Casos", 
            light_color = "pink",
            dark_color = "purple")
mapa_delitos
```

```{r}
# Coordenadas de los distritos fiscales de Puerto Rico
coordenadas_pr <- data.frame(
  `FISCALIA DISTRITO` = c("Aguadilla", "Aibonito", "Arecibo", "Bayamón", "Caguas", "Carolina", "Fajardo", "Guayama", "Humacao", "Mayagüez", "Ponce", "San Juan", "Utuado", "Vega Baja"),
  longitud = c(-67.1541, -66.2625, -66.7181, -66.1653, -66.0399, -65.9665,
               -65.6522, -66.1109, -65.8329, -67.1457, -66.6168, -66.1057, -66.688, -66.4337),
  latitud = c(18.4274, 18.142, 18.4503, 18.3798, 18.2343, 18.3802,
              18.3258, 17.9756, 18.148, 18.201, 18.0108, 18.4655, 18.2635, 18.4461)
)


# Filtrar y fusionar datos
delitos_2020 <- subset(merge(dfDeli, coordenadas_pr, by.x = "FISCALIA DISTRITO", by.y = "FISCALIA.DISTRITO"), Año == 2020 & Delito == "Art2.8")

# Crear una paleta de colores basada en el atributo deseado
colores <- colorFactor(
  palette = c('#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf', '#aec7e8', '#ffbb78'),  # Colores disponibles
  domain = distritos_fiscales$GROUP  # Atributo de las regiones agrícolas utilizado para generar la paleta de colores
)

# Crear el mapa Leaflet
m <- leaflet() %>% 
  addTiles(urlTemplate = "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png") %>%  # Agregar capa de teselas base
  fitBounds(-67.5, 17.8, -65, 18.6) %>%  # Ajustar límites del mapa
  setView(-66.3, 18.2, zoom = 8.5) %>%  # Establecer vista centrada en Puerto Rico
  setMaxBounds(lng1 = -67.5, lat1 = 17.8, lng2 = -65, lat2 = 18.6) %>%
  addPolygons(
    data = distritos_fiscales,  # Añadir polígonos de las regiones agrícolas
    fillColor = ~colores(GROUP), # Asignar colores a cada región agrícola basados en el atributo STATE
    color = "",
    fillOpacity = 0.3,
    weight = 2,
    highlight = highlightOptions(
    weight = 5,  # Grosor del borde al resaltar
    color = "white",  # Color del borde al resaltar
    fillOpacity = 0.7,  # Opacidad del relleno al resaltar
    )
    ) %>%
  addMarkers(
    lng = coordenadas_pr$longitud, 
    lat = coordenadas_pr$latitud,
    popup = paste("Distrito:", coordenadas_pr$`FISCALIA DISTRITO`)
    )  # Añadir marcadores en los pueblos seleccionados
# Mostrar el mapa
m
```