---
title: "DeptJusticiaTransform"
author: "Félix A. Báez Santiago"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(zoo)
library(here)
path <- here("data", "Departamento_de_Justicia", "/")
```

Funcion para manejar datos missing
```{r}
# funcion para convertir columna con varios tipos de datos a numerico
convert_mixed_columns <- function(data) {
  mixed_columns <- sapply(data, function(col) any(is.character(col) & !is.na(as.numeric(col))))
  mixed_columns_names <- names(mixed_columns)[mixed_columns]
  
  for (col in mixed_columns_names) {
    data[[col]] <- ifelse(data[[col]] == "N/A", NA, as.character(data[[col]]))
    data[[col]] <- as.numeric(data[[col]])
  }
  
  return(data)
}
```

```{r}
# importando delitos del 2020
deli2020 <- read_excel(paste0(path, "djDelitos2020.xlsx")) %>% 
  convert_mixed_columns() %>%
  mutate(Año = "2020")

# importando delitos del 2021
deli2021 <- read_excel(paste0(path, "djDelitos2021.xlsx")) %>% 
  convert_mixed_columns() %>%
  mutate(Año = "2021")

# importando delitos del 2022
deli2022 <- read_excel(paste0(path, "djDelitos2022.xlsx")) %>% 
  convert_mixed_columns() %>%
  mutate(Año = "2022")

# importando delitos del 2023
deli2023 <- read_excel(paste0(path, "djDelitos2023.xlsx")) %>% 
  convert_mixed_columns() %>%
  mutate(Año = "2023")

pepe <- full_join(deli2020, deli2021) %>% 
  full_join(deli2022) %>%
  full_join(deli2023) %>%
  select(!TOTAL) %>%
  pivot_longer(-c(`FISCALIA DISTRITO`, Año), names_to = "Delito", values_to = "Numero de Casos")
```

