---
title: "Visualizaciones Preliminares: Departamento de Justicia"
author: "Félix A Báez Santiago"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, echo=FALSE, message=FALSE}
library(leaflet)
library(tidyverse)
library(readxl)
library(zoo)
library(here)
library(lubridate)
library(sf)
path <- here("data", "Departamento_de_Justicia//")
```

Funcion para manejar datos missing
```{r, warning=FALSE, echo=FALSE, message=FALSE}
# funcion para convertir columna con varios tipos de datos a numerico
convert_mixed_columns <- function(data) {
  mixed_columns <- sapply(data, function(col) any(is.character(col) & !is.na(as.numeric(col))))
  mixed_columns_names <- names(mixed_columns)[mixed_columns]
  
  for (col in mixed_columns_names) {
    data[[col]] <- ifelse(data[[col]] == "N/A", NA, as.character(data[[col]]))
    data[[col]] <- as.numeric(data[[col]])
  }
  
  return(data)
}
```

## Delitos a la Ley 54, casos radicados por jurisdicción y articulo de la Ley de Violencia Domestica, año 2020 a *2023
```{r, warning=FALSE, echo=FALSE, message=FALSE}
# importando delitos del 2020
deli2020 <- read_excel(paste0(path, "djDelitos2020.xlsx")) %>% 
  convert_mixed_columns() %>%
  mutate(Año = "2020") %>% select(-TOTAL) %>%
  pivot_longer(-c(`FISCALIA DISTRITO`, Año), names_to = "Delito", values_to = "Casos") %>%
  filter(!grepl("TOTAL", `FISCALIA DISTRITO`, ignore.case = TRUE))

# importando delitos del 2021
deli2021 <- read_excel(paste0(path, "djDelitos2021.xlsx")) %>%
  convert_mixed_columns() %>%
  mutate(Año = "2021") %>% select(-TOTAL) %>% 
  pivot_longer(-c(`FISCALIA DISTRITO`, Año), names_to = "Delito", values_to = "Casos") %>%
  filter(!grepl("TOTAL", `FISCALIA DISTRITO`, ignore.case = TRUE))

# importando delitos del 2022
deli2022 <- read_excel(paste0(path, "djDelitos2022.xlsx")) %>%
  convert_mixed_columns() %>%
  mutate(Año = "2022") %>% select(-TOTAL) %>%
  pivot_longer(-c(`FISCALIA DISTRITO`, Año), names_to = "Delito", values_to = "Casos") %>%
  filter(!grepl("TOTAL", `FISCALIA DISTRITO`, ignore.case = TRUE))

# importando delitos del 2023
deli2023 <- read_excel(paste0(path, "djDelitos2023.xlsx")) %>%
  convert_mixed_columns() %>%
  mutate(Año = "2023") %>% select(-TOTAL) %>%
  pivot_longer(-c(`FISCALIA DISTRITO`, Año), names_to = "Delito", values_to = "Casos") %>%
  filter(!grepl("TOTAL", `FISCALIA DISTRITO`, ignore.case = TRUE))

deliDF <- full_join(deli2020, deli2021) %>% 
  full_join(deli2022) %>%
  full_join(deli2023) %>%
  mutate(
    Año = as.factor(Año)
    )
deliDF
```

```{r}
# Crear un dataframe con las coordenadas de las regiones agrícolas
regiones_agricolas <- sf::st_read("https://raw.githubusercontent.com/LuisAponteLopez/PuertoRicoCoordenadas/main/municipios.json")

# Coordenadas de los distritos fiscales de Puerto Rico
coordenadas_pr <- data.frame(
  `FISCALIA DISTRITO` = c("AGUADILLA", "AIBONITO", "ARECIBO", "BAYAMÓN", "CAGUAS", "CAROLINA",
                          "FAJARDO", "GUAYAMA", "HUMACAO", "MAYAGÜEZ", "PONCE", "SAN JUAN", "UTUADO"),
  longitud = c(-67.1541, -66.2625, -66.7181, -66.1653, -66.0399, -65.9665,
               -65.6522, -66.1109, -65.8329, -67.1457, -66.6168, -66.1057, -66.688),
  latitud = c(18.4274, 18.142, 18.4503, 18.3798, 18.2343, 18.3802,
              18.3258, 17.9756, 18.148, 18.201, 18.0108, 18.4655, 18.2635)
)

# Crear una paleta de colores basada en el atributo deseado
colores <- colorFactor(
  palette = c('cyan', 'magenta', 'yellow', 'violet', 'orange', 'limegreen', 'darkblue', 'brown'),  # Colores disponibles
  domain = regiones_agricolas$STATE  # Atributo de las regiones agrícolas utilizado para generar la paleta de colores
)

# Filtrar y fusionar datos
delitos_2020 <- subset(merge(deliDF, coordenadas_pr, by.x = "FISCALIA DISTRITO", by.y = "FISCALIA.DISTRITO"), Año == 2020 & Delito == "Art2.8")

# Crear el mapa Leaflet
m <- leaflet() %>% 
  addTiles() %>%  # Agregar capa de teselas base
  fitBounds(-67.1541, 18.2635, -65.6522, 18.4655) %>%  # Ajustar límites del mapa
  setView(-66.1057, 18.2376, zoom = 9) %>%  # Establecer vista centrada en Puerto Rico
  # addCircleMarkers(data = delitos_2020,  # Añadir marcadores circulares
  #                  lng = ~longitud,
  #                  lat = ~latitud,
  #                  radius = sqrt(delitos_2020$Casos) * 5,  # Tamaño del marcador basado en la raíz cuadrada de los casos
  #                  color = "red",
  #                  fillOpacity = 0.8,
  #                  stroke = FALSE,
  #                  popup = paste("Distrito:", delitos_2020$`FISCALIA DISTRITO`, "<br>", "Casos:", delitos_2020$Casos)) %>%  # Popup con información
  addPolygons(data = regiones_agricolas,  # Añadir polígonos de las regiones agrícolas
              fillColor = ~colores(STATE), # Asignar colores a cada región agrícola basados en el atributo STATE
              color = "green",
              fillOpacity = 0.3,
              weight = 2,
              highlight = highlightOptions(
                weight = 5,  # Grosor del borde al resaltar
                color = "white",  # Color del borde al resaltar
                fillOpacity = 0.7,  # Opacidad del relleno al resaltar
                bringToFront = TRUE
              )) %>%
  addMarkers(lng = coordenadas_pr$longitud, 
             lat = coordenadas_pr$latitud,
             popup = paste("Distrito:", coordenadas_pr$`FISCALIA DISTRITO`))  # Añadir marcadores en los pueblos seleccionados
# Mostrar el mapa
m
```

```{r}
# Definir una paleta de colores para las regiones agrícolas
colores_region_agricola <- c('cyan', 'magenta', 'yellow', 'violet', 'orange', 'limegreen', 'darkblue', 'brown')

# Crear el mapa Leaflet
m <- leaflet() %>% 
  addTiles() %>%  # Agregar capa de teselas base
  fitBounds(-67.1541, 18.2635, -65.6522, 18.4655) %>%  # Ajustar límites del mapa
  setView(-66.1057, 18.2376, zoom = 9) %>%  # Establecer vista centrada en Puerto Rico
  addPolygons(data = regiones_agricolas,  # Añadir polígonos de las regiones agrícolas
              fillColor = ~colores_region_agricola[as.numeric(STATE)], # Asignar colores a cada región agrícola basados en el atributo STATE
              #color = "green",
              fillOpacity = 0.3,
              weight = 2,
              highlight = highlightOptions(
                weight = 5,  # Grosor del borde al resaltar
                color = "white",  # Color del borde al resaltar
                fillOpacity = 0.7,  # Opacidad del relleno al resaltar
                bringToFront = TRUE
              )) %>%
  addMarkers(lng = coordenadas_pr$longitud, 
             lat = coordenadas_pr$latitud,
             popup = paste("Distrito:", coordenadas_pr$`FISCALIA DISTRITO`))  # Añadir marcadores en los pueblos seleccionados
# Mostrar el mapa
m
```


```{r}
# Crear un dataframe de asignación de pueblos a regiones policíacas
asignacion <- data.frame(
  Area_Policiaca = c("Aibonito", "Aguadilla", "Arecibo", "Bayamón", "Caguas", "Carolina", 
                     "Fajardo", "Guayama", "Humacao", "Mayagüez", "Ponce", "San Juan", "Utuado"),
  Pueblo = c("Aibonito, Barranquitas, Coamo, Comerío, Orocovis", 
              "Aguadilla, Aguada, Isabela, Moca, Rincón, San Sebastián",
              "Arecibo, Barceloneta, Camuy, Ciales, Florida, Hatillo, Manatí, Morovis, Quebradillas",
              "Bayamón, Cataño, Guaynabo, Toa Alta, Dorado, Naranjito, Corozal, Vega Alta, Vega Baja",
              "Caguas, Aguas Buenas, Cidra, Gurabo, Juntos, San Lorenzo",
              "Carolina, Trujillo Alto, Canóvanas, Loíza",
              "Fajardo, Ceiba, Culebra, Luquillo, Río Grande, Vieques",
              "Guayama, Arroyo, Cayey, Patillas, Salinas, Santa Isabel",
              "Humacao, Las Piedras, Maunabo, Yabucoa",
              "Mayagüez, Añasco, Cabo Rojo, Hormigueros, Lajas, Las Marías, Maricao, Sabana Grande, San Germán",
              "Ponce, Guánica, Guayanilla, Juana Díaz, Peñuelas, Villalba, Yauco",
              "San Juan",
              "Utuado, Adjuntas, Jayuya, Lares"),
  stringsAsFactors = FALSE
)

# Dividir la columna 'Pueblos' en filas para cada pueblo
pueblos_por_area <- tidyr::separate_rows(asignacion, Pueblo, sep = ", ")
pueblos_por_area

```

```{r}
# Crear dataframe de áreas policiacas y pueblos
areas_policiacas <- data.frame(
  Area_Policiaca = c("Aibonito", "Aguadilla", "Arecibo", "Bayamón", "Caguas", "Carolina", "Fajardo", "Guayama", "Humacao", "Mayagüez", "Ponce", "San Juan", "Utuado"),
  Pueblos = c("Aibonito, Barranquitas, Coamo, Comerío, Orocovis", "Aguadilla, Aguada, Isabela, Moca, Rincón, San Sebastián", "Arecibo, Barceloneta, Camuy, Ciales, Florida, Hatillo, Manatí, Morovis, Quebradillas", "Bayamón, Cataño, Guaynabo, Toa Alta, Dorado, Naranjito, Corozal, Vega Alta, Vega Baja", "Caguas, Aguas Buenas, Cidra, Gurabo, Juntos, San Lorenzo", "Carolina, Trujillo Alto, Canóvanas, Loíza", "Fajardo, Ceiba, Culebra, Luquillo, Río Grande, Vieques", "Guayama, Arroyo, Cayey, Patillas, Salinas, Santa Isabel", "Humacao, Las Piedras, Maunabo, Yabucoa", "Mayagüez, Añasco, Cabo Rojo, Hormigueros, Lajas, Las Marías, Maricao, Sabana Grande, San Germán", "Ponce, Guánica, Guayanilla, Juana Díaz, Peñuelas, Villalba, Yauco", "San Juan", "Utuado, Adjuntas, Jayuya, Lares")
)

```


```{r, warning=FALSE, echo=FALSE, message=FALSE}
# limites <- c(0, sum(deliDF$Casos, na.rm = TRUE) + 20)
# 
# # Obtener los años
# año_seleccionado <- unique(deliDF$Año)
# 
# # Loop para crear y mostrar las gráficas
# for (i in seq_along(año_seleccionado)) {
#   plot_data <- subset(deliDF, Año == año_seleccionado[i])
#   
#   # Crear la gráfica
#   p <- ggplot(subset(deliDF, Año == año_seleccionado[i]), aes(x = Delito, y = Casos, fill = Delito)) +
#   geom_bar(stat = "identity") +
#   labs(title = paste("Número de Casos por Delito", año_seleccionado[i]), x = "Delito Cometido", y = "Número de Casos", fill = "Delito Cometido") +
#   #coord_cartesian(ylim = limites) +
#   theme_minimal() + coord_flip()
#   
#   # Mostrar la gráfica
#   print(p)
# }
ggplot(deliDF, aes(x = Año, y = Casos, color = `FISCALIA DISTRITO`, group = `FISCALIA DISTRITO`)) +
  geom_line() +
  geom_point() +
  labs(title = "Tendencia de Casos a lo Largo del Tiempo por Fiscalía de Distrito", x = "Año", y = "Número de Casos") +
  theme_minimal() +
  facet_wrap(~Delito , scales = "fixed") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

df2 <- deliDF %>%
  filter(`FISCALIA DISTRITO` %in% c("AGUADILLA", "BAYAMÓN"))

ggplot(df2, aes(x = Año, y = Casos, color = `FISCALIA DISTRITO`, group = `FISCALIA DISTRITO`)) +
  geom_line() +
  geom_point() +
  labs(title = "Tendencia de Casos a lo Largo del Tiempo por Fiscalía de Distrito", x = "Año", y = "Número de Casos") +
  theme_minimal() +
  facet_wrap(~Delito , scales = "fixed") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(deliDF, aes(x = Delito, y = Casos, fill = Delito)) +
  geom_bar(stat = "identity") +
  labs(title = "Número de Casos por Delito (Año 2023)", x = "Delito Cometido", y = "Número de Casos", fill = "Delito Cometido") +
  facet_wrap(~ Año, scales = "fixed") +
  theme_minimal() + coord_flip()

ggplot(deliDF, aes(x = factor(Año), y = Casos)) +
  geom_boxplot() +
  labs(title = "Distribución de Casos por Delito", x = "Año", y = "Casos") +
  theme_minimal() +
  facet_wrap(~Delito, scales = "fixed")
```

```{r, warning=FALSE, echo=FALSE, message=FALSE}
# # Obtener los años
# delito_seleccionado <- unique(deliDF$Delito)
# 
# # Loop para crear y mostrar las gráficas
# for (i in seq_along(delito_seleccionado)) {
#   plot_data <- subset(deliDF, Delito == delito_seleccionado[i])
#   
#   # Crear la gráfica
#   p <- ggplot(subset(deliDF, Delito == delito_seleccionado[i]), aes(x = factor(Año), y = Casos)) +
#   geom_boxplot() +
#   labs(title = paste("Distribución de Casos por Distrito para el Delito", delito_seleccionado[i]), x = "Año", y = "Casos") +
#   #coord_cartesian(ylim = limites) +
#   theme_minimal()
#   
#   # Mostrar la gráfica
#   print(p)
# }

# Obtener los delitos
# delito_seleccionado <- unique(deliDF$Delito)
# año_seleccionado <- unique(deliDF$Año)
# 
# # Loop para crear y mostrar las gráficas
# for (i in seq_along(año_seleccionado)) {
#   for (j in seq_along(delito_seleccionado)){
#     plot_data <- subset(deliDF, Delito == delito_seleccionado[j] & Año == año_seleccionado[i])
#   
#     # Crear la gráfica
#     p <- ggplot(subset(deliDF, Año == año_seleccionado[i] & Delito == delito_seleccionado[j]), aes(x = `FISCALIA DISTRITO`, y = Casos, fill = `FISCALIA DISTRITO`)) +
#   geom_bar(stat = "identity", width = 0.7) +
#   labs(title = paste("Distribución de Casos por Distrito Fiscal para", delito_seleccionado[j], "en el", año_seleccionado[i]), x = "Fiscalía Distrito", y = "Casos", fill = "Distrito Fiscal") +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1))
#   
#     # Mostrar la gráfica
#     print(p)
#   }
# }

# ggplot(deliDF, aes(x = Año, y = Casos, fill = Delito)) +
#   geom_bar(stat = "identity", position = "dodge") +
#   labs(title = "Comparación de Numero de Casos por Delito a lo largo de los Años", x = "Año", y = "Casos", fill = "Delito") +
#   theme_minimal() 
```

## Pruebas Estadisticas
```{r, warning=FALSE, echo=FALSE, message=FALSE}
# modelo de regresion entre año y el delito del articulo 2.8
modelo_regresion_2.8 <- lm(Casos ~ as.factor(Año), data = subset(deliDF, Delito == "Art2.8"))
summary(modelo_regresion_2.8)

# modelo de regresion entre año y el delito del articulo 3.1
modelo_regresion_3.1 <- lm(Casos ~ as.factor(Año), data = subset(deliDF, Delito == "Art3.1"))
summary(modelo_regresion_3.1)

# modelo de regresion entre año y el delito del articulo 3.2
modelo_regresion_3.2 <- lm(Casos ~ as.factor(Año), data = subset(deliDF, Delito == "Art3.2"))
summary(modelo_regresion_3.2)

# modelo de regresion entre año y el delito del articulo 3.3
modelo_regresion_3.3 <- lm(Casos ~ as.factor(Año), data = subset(deliDF, Delito == "Art3.3"))
summary(modelo_regresion_3.3)

# modelo de regresion entre año y el delito del articulo 3.4
modelo_regresion_3.4 <- lm(Casos ~ as.factor(Año), data = subset(deliDF, Delito == "Art3.4"))
summary(modelo_regresion_3.4)

# modelo de regresion entre año y el delito del articulo 3.5
modelo_regresion_3.5 <- lm(Casos ~ as.factor(Año), data = subset(deliDF, Delito == "Art3.5"))
summary(modelo_regresion_3.5)

# modelo de regresion entre año y el delito del articulo 3.5
modelo_regresion_todos_arts <- lm(Casos ~ as.factor(Año), data = deliDF)
summary(modelo_regresion_todos_arts)
```

## Registro de personas convictas por violencia doméstica, según el municipio y el sexo (acumulado desde el 2018 a *2023)
```{r, warning=FALSE, echo=FALSE, message=FALSE}
casosMapa <- read_excel(paste0(path, "djCasosMapa.xlsx")) %>% 
  convert_mixed_columns()

convicMuni <- read_excel(paste0(path, "djConvicMuni.xlsx")) %>% 
  convert_mixed_columns()

convic <- full_join(casosMapa, convicMuni) %>%
  na.omit()
convic
```

```{r, warning=FALSE, echo=FALSE, message=FALSE}
# # Crear un objeto sf directamente desde las columnas lng y lat de convic
# convic_sf <- st_as_sf(convic, coords = c("lng", "lat"), crs = 4326)
# 
# # Cargar los datos espaciales de Puerto Rico (usando un objeto sf vacío)
# pr_map <- st_read(paste0(path,"mapas/mapaPR.shp"))
#                               , package="sf"))[0, ]
# 
# # Unir los datos de convic con el mapa
# pr_map <- st_join(pr_map, convic_sf)
# 
# # Graficar el mapa
# ggplot() +
#   geom_sf(data = pr_map, aes(fill = Casos), color = "white", lwd = 0.2) +
#   scale_fill_viridis_c(name = "Casos", option = "plasma", trans = "sqrt") +
#   theme_minimal() +
#   ggtitle("Casos en Puerto Rico por Municipio") +
#   theme(legend.position = "bottom")
```

