name: Run on push main or master

# Controla cuándo se ejecuta la acción
on:
  # Desencadena el workflow en eventos push a main o master
  push:
    branches: [ main, master ]

  # Permite ejecutar el workflow manualmente desde la pestaña de Actions
  workflow_dispatch:

# Definición de los trabajos (jobs)
jobs:
  # Este workflow contiene un solo job llamado "build"
  build:
    # Tipo de runner en el que se ejecutará el job
    runs-on: ubuntu-latest

    # Secuencia de pasos a ejecutar como parte del job
    steps:
      # Revisa el repositorio bajo $GITHUB_WORKSPACE para que el job pueda acceder a él
      - uses: actions/checkout@v2

      # Construye la imagen Docker y le da el nombre main
      - name: Build image
        run: docker build -t main .

      # Ejecuta la imagen Docker y usa los secretos de GitHub
      - name: Execute
        run: >
          docker run 
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }} 
          -e TOKEN=${{ secrets.TOKEN }} 
          -e SECRET=${{ secrets.SECRET }} 
          main
