name: Run on pull request; deploy Shiny App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Construir la imagen de Docker
      - name: Build image
        run: docker build -t main .

      # Ejecutar el contenedor de Docker e inyectar los secretos
      - name: Run Docker container with Shiny secrets
        env:
          SHINY_ACC_NAME: ${{ secrets.SHINY_ACC_NAME }}
          TOKEN: ${{ secrets.TOKEN }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          docker run \
          -e SHINY_ACC_NAME=$SHINY_ACC_NAME \
          -e TOKEN=$TOKEN \
          -e SECRET=$SECRET \
          main
